// src/types/collaboration.ts
// Advanced Collaboration, Knowledge Graph, and Automation Types

export interface Workspace {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  color?: string;
  members: WorkspaceMember[];
  roles: WorkspaceRole[];
  settings: WorkspaceSettings;
  createdAt: string;
  updatedAt: string;
}

export interface WorkspaceMember {
  userId: string;
  role: 'owner' | 'admin' | 'editor' | 'viewer';
  invitedAt: string;
  joinedAt?: string;
  status: 'active' | 'invited' | 'suspended';
  permissions: PermissionSet;
}

export interface PermissionSet {
  canEdit: boolean;
  canDelete: boolean;
  canShare: boolean;
  canInvite: boolean;
  canManageBilling: boolean;
  canAccessAnalytics: boolean;
}

export interface WorkspaceRole {
  id: string;
  name: string;
  permissions: PermissionSet;
}

export interface WorkspaceSettings {
  visibility: 'private' | 'team' | 'public';
  allowGuests: boolean;
  require2FA: boolean;
  defaultLanguage: string;
  branding?: {
    logoUrl?: string;
    primaryColor?: string;
  };
}

export interface CollaborationSession {
  id: string;
  resourceId: string; // Note ID, Task ID, etc.
  resourceType: 'note' | 'task' | 'whiteboard' | 'document';
  activeUsers: ActiveUser[];
  cursors: Record<string, CursorPosition>;
  lastActivity: string;
}

export interface ActiveUser {
  userId: string;
  name: string;
  avatar?: string;
  color: string; // Cursor color
  lastSeen: string;
  isTyping: boolean;
}

export interface CursorPosition {
  line: number;
  column: number;
  selectionStart?: number;
  selectionEnd?: number;
}

export interface Comment {
  id: string;
  resourceId: string;
  parentId?: string;
  authorId: string;
  content: string;
  resolved: boolean;
  resolvedBy?: string;
  createdAt: string;
  updatedAt: string;
  mentions: string[]; // User IDs
  attachments?: Attachment[];
  reactions: Reaction[];
}

export interface Reaction {
  emoji: string;
  userId: string;
  timestamp: string;
}

export interface ActivityLog {
  id: string;
  workspaceId: string;
  userId: string;
  action: 'create' | 'update' | 'delete' | 'comment' | 'share' | 'move';
  targetType: 'note' | 'task' | 'event' | 'contact' | 'file';
  targetId: string;
  targetName: string;
  metadata: Record<string, any>;
  timestamp: string;
  ipAddress?: string;
}

// Knowledge Graph Types
export interface KnowledgeNode {
  id: string;
  type: 'note' | 'task' | 'event' | 'contact' | 'concept' | 'resource';
  title: string;
  summary?: string;
  color?: string;
  icon?: string;
  position?: { x: number; y: number }; // For manual layout
  metadata: Record<string, any>;
  clusterId?: string;
}

export interface KnowledgeEdge {
  id: string;
  sourceId: string;
  targetId: string;
  type: 'links_to' | 'references' | 'depends_on' | 'related_to' | 'parent_of' | 'derived_from';
  strength: number; // 0-1 confidence score
  label?: string;
  createdAt: string;
}

export interface KnowledgeCluster {
  id: string;
  name: string;
  description?: string;
  nodeIds: string[];
  color: string;
  autoGenerated: boolean;
}

export interface GraphLayout {
  nodes: KnowledgeNode[];
  edges: KnowledgeEdge[];
  clusters: KnowledgeCluster[];
  viewport: { x: number; y: number; zoom: number };
}

// Automation & Workflow Types
export interface Workflow {
  id: string;
  name: string;
  description?: string;
  trigger: WorkflowTrigger;
  actions: WorkflowAction[];
  conditions?: WorkflowCondition[];
  isActive: boolean;
  lastRun?: string;
  runCount: number;
  createdBy: string;
}

export interface WorkflowTrigger {
  type: 'event' | 'schedule' | 'webhook' | 'manual';
  eventType?: 'note_created' | 'task_completed' | 'email_received' | 'meeting_ended';
  cronExpression?: string; // For schedule triggers
  webhookUrl?: string;
  filters?: Record<string, any>;
}

export interface WorkflowAction {
  id: string;
  type: 'create_note' | 'create_task' | 'send_email' | 'update_crm' | 'slack_notify' | 'ai_summarize' | 'move_card';
  config: Record<string, any>;
  order: number;
}

export interface WorkflowCondition {
  field: string;
  operator: 'equals' | 'contains' | 'greater_than' | 'less_than' | 'is_empty' | 'regex';
  value: any;
  logic: 'and' | 'or';
}

export interface AutomationLog {
  id: string;
  workflowId: string;
  triggeredAt: string;
  status: 'success' | 'failed' | 'running';
  inputData: any;
  outputData?: any;
  error?: string;
  executionTimeMs: number;
}

// Universal Search Types
export interface SearchResult {
  id: string;
  type: 'note' | 'task' | 'email' | 'contact' | 'event' | 'file' | 'transcript';
  title: string;
  snippet: string; // Highlighted match
  score: number; // Relevance score
  metadata: {
    createdAt: string;
    author?: string;
    tags?: string[];
    folder?: string;
  };
  contextPath: string[]; // Breadcrumb trail
}

export interface SearchFacet {
  name: string;
  values: { value: string; count: number }[];
}

export interface SearchQuery {
  query: string;
  filters: {
    types?: string[];
    dateRange?: { start: string; end: string };
    tags?: string[];
    authors?: string[];
    workspaces?: string[];
  };
  sortBy: 'relevance' | 'date' | 'alphabetical';
  limit: number;
  offset: number;
}

// AI Assistant Context
export interface AssistantContext {
  currentView: string;
  selectedItems: string[]; // IDs of selected notes/tasks
  recentActivity: ActivityLog[];
  userPreferences: {
    tone: 'professional' | 'casual' | 'concise';
    detailLevel: 'brief' | 'detailed';
  };
}

export interface AssistantMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  relatedEntities?: SearchResult[];
  suggestedActions?: SuggestedAction[];
}

export interface SuggestedAction {
  label: string;
  type: 'create_task' | 'schedule_event' | 'search' | 'summarize' | 'generate_content';
  payload: any;
  icon: string;
}
